version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:3.1.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs mysql-client
            gem install bundler
            bundle install --jobs=4 --retry=3
      - run:
          name: Database setup
          command: |
            cp config/database.yml.ci config/database.yml
            bundle exec rails db:create db:schema:load
      - run:
          name: Run tests
          command: |
            bundle exec rails test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
